apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-from-prvate-repo
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
    spec:
      containers:
      - name: test-container
        image: # 도커 허브 프라이빗 저장소 이미지 이름 입력
        args: ['tail', '-f', '/dev/null']
      imagePullSecrets:
      - name: registry-auth-registry